### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VisionR1** [mikegabriel/pspgo-baryon-sweeper-jig-guide#1]
If you read this https://github.com/khubik2/pysweeper/issues/14
Can get it with USB to Serial Module - CP2102 with some modify ?

And some news: https://www.psdevwiki.com/psp/images/f/f4/GPEHSYqW8AAD6oC.jpg

**Comment by mikegabriel** [comment]
Sorry but I am not sure, you did receive some feedback in that other thread but I would recommend sourcing a FT232RL online since that is known to work.
